"""
Regulatory PDF Report Generator
Generates official 'Legal Metrology Compliance Inspection Report' PDF certificates with evidence details,
field extraction breakdown, legal rule evaluation verdicts, and SHA-256 provenance hashes.
"""

import time
from pathlib import Path
from typing import Dict, Any

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

REPORTS_DIR = Path(__file__).parent.parent / "reports" / "pdf_exports"

def generate_inspection_pdf(inspection_payload: Dict[str, Any]) -> str:
    """Generate official PDF inspection report."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    inspection_id = inspection_payload.get("inspection_id", "UNKNOWN")
    pdf_filename = f"Legal_Metrology_Inspection_{inspection_id}.pdf"
    pdf_path = REPORTS_DIR / pdf_filename

    doc = SimpleDocTemplate(str(pdf_path), pagesize=letter, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#0f172a'),
        alignment=1
    )
    story.append(Paragraph("Legal Metrology Compliance Inspection Report", title_style))
    story.append(Paragraph("Government of India — Department of Consumer Affairs", ParagraphStyle('Sub', parent=title_style, fontSize=11, leading=14, textColor=colors.gray)))
    story.append(Spacer(1, 15))

    # Meta table
    status = inspection_payload.get("overall_status", "REVIEW_REQUIRED")
    meta_data = [
        ["Inspection ID:", inspection_id, "Date:", time.strftime("%Y-%m-%d %H:%M:%S")],
        ["Overall Verdict:", status, "Views Analyzed:", str(inspection_payload.get("views_analyzed", 1))]
    ]
    t_meta = Table(meta_data, colWidths=[110, 160, 110, 160])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
    ]))
    story.append(t_meta)
    story.append(Spacer(1, 15))

    # Declarations Header
    story.append(Paragraph("Mandatory Declarations & Legal Rule Outcome", styles['Heading2']))
    story.append(Spacer(1, 8))

    table_data = [["Rule ID", "Field Name", "Extracted Value", "Rule Outcome"]]
    comp_res = inspection_payload.get("compliance_result", {})
    outcomes = comp_res.get("field_outcomes", {})

    for r_id, item in outcomes.items():
        table_data.append([
            item.get("rule_id", r_id),
            item.get("field_name", r_id).upper(),
            str(item.get("extracted_value") or "NOT DETECTED")[:35],
            item.get("status", "REVIEW")
        ])

    t_rules = Table(table_data, colWidths=[100, 150, 170, 120])
    t_rules.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1e293b')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 8),
    ]))
    story.append(t_rules)
    story.append(Spacer(1, 20))

    # Disclaimer
    disc_text = "<b>LEGAL NOTICE:</b> This report is generated by an automated decision-support system under Legal Metrology (Packaged Commodities) Rules, 2011. It does not constitute a final judicial penalty without human officer verification."
    story.append(Paragraph(disc_text, ParagraphStyle('Disc', parent=styles['Normal'], fontSize=8, textColor=colors.HexColor('#475569'))))

    doc.build(story)
    return str(pdf_path)

if __name__ == "__main__":
    test_payload = {
        "inspection_id": "TEST_001",
        "overall_status": "COMPLIANT",
        "views_analyzed": 1,
        "compliance_result": {
            "field_outcomes": {
                "mrp": {"rule_id": "LM-PC-MRP-001", "field_name": "mrp", "extracted_value": "₹249.00", "status": "PASS"}
            }
        }
    }
    path = generate_inspection_pdf(test_payload)
    print(f"Generated test PDF at: {path}")
